baseURL = "https://jon.bo/"
languageCode = "en-us"

theme = "hello-friend"
paginate = 5

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # "light" or "dark"
  defaultTheme = "dark"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 4
  # Show reading time in minutes for posts
  showReadingTime = false

[languages]
  [languages.en]
    title = "up & to the right"
    subtitle = "Jonathan Borichevskiy"
    keywords = ""
    copyright = "<a href='/about'>jon.bo</a>"
    menuMore = "More"
    writtenBy = "Written by"
    readMore = "Read"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"

    [languages.en.params.logo]
      logoText = "up & to the right"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "writing"
        name = "writing"
        url = "/posts"
        weight=1
      [[languages.en.menu.main]]
        identifier = "reading-list"
        name = "reading list"
        url = "/books"